export const ENDPOINTS = {
    AUTH: {
        REGISTER: "/auth/register",
        VERIFY_OTP: "/auth/verify-otp",
        RESEND_OTP: "/auth/resend-otp",
        LOGIN: "/auth/login",
        REFRESH: "/auth/refresh",
        LOGOUT: "/auth/logout",
        FORGOT_PASSWORD: "/auth/forgot-password",
        RESET_PASSWORD: "/auth/reset-password",
    },
    COMPANY: {
        EMPLOYEES: "/company/employees",
        ADD_EMPLOYEE: "/company/employee/add",
        TOGGLE_BLOCK_EMPLOYEE: (userId: string) => `/company/employee/${userId}/toggle-block`,
        GET_EMPLOYEE_DETAILS: (userId: string) => `/company/employee/${userId}`,
        UPDATE_EMPLOYEE_DETAILS: (userId: string) => `/company/employee/${userId}`,
        GET_UNASSIGNED_EMPLOYEES: "/company/employees/unassigned",
        ASSIGN_TEAM_TO_EMPLOYEE: (employeeId: string) => `/company/employee/${employeeId}/assign-team`,
        TEAMS: "/company/teams",
        UPDATE_TEAM: (teamId: string) => `/company/team/${teamId}`,
        DELETE_TEAM: (teamId: string) => `/company/team/${teamId}`,
    },
    USER: {
        PROFILE: "/user/profile",
        CHANGE_PASSWORD: "/user/change-password",
    },
    PROJECTS: {
        BASE: "/projects",
        BY_ID: (id: string) => `/projects/${id}`,
    },
    USER_STORIES: {
        BASE: "/user-stories",
        BY_PROJECT: (projectId: string) => `/user-stories/project/${projectId}`,
        BY_SPRINT: (sprintId: string) => `/user-stories/sprint/${sprintId}`,
        BY_ID: (id: string) => `/user-stories/${id}`,
        ASSIGN: (id: string) => `/user-stories/${id}/assign`,
    },
    TEAMS: {
        BASE: "/teams",
        DIRECTORY: "/teams/directory",
    },
    SPRINTS: {
        BASE: "/sprints",
        BY_ID: (id: string) => `/sprints/${id}`,
    },
    TASKS: {
        BASE: "/tasks",
        BY_STORY: (storyId: string) => `/tasks/story/${storyId}`,
        BY_ID: (id: string) => `/tasks/${id}`,
        ASSIGN: (id: string) => `/tasks/${id}/assign`,
        ASSIGNED: "/tasks/assigned",
        TEAM: "/tasks/team",
        ALL: "/tasks/all",
    },
};
