export const ENDPOINTS = {
    AUTH: {
        REGISTER: "/auth/register",
        VERIFY_OTP: "/auth/verify-otp",
        RESEND_OTP: "/auth/resend-otp",
        LOGIN: "/auth/login",
        REFRESH: "/auth/refresh",
        LOGOUT: "/auth/logout",
        FORGOT_PASSWORD: "/auth/forgot-password",
        RESET_PASSWORD: "/auth/reset-password",
    },
    COMPANY: {
        EMPLOYEES: "/company/employees",
        ADD_EMPLOYEE: "/company/employee/add",
        TOGGLE_BLOCK_EMPLOYEE: (userId: string) => `/company/employee/${userId}/toggle-block`,
        GET_EMPLOYEE_DETAILS: (userId: string) => `/company/employee/${userId}`,
        UPDATE_EMPLOYEE_DETAILS: (userId: string) => `/company/employee/${userId}`,
        GET_UNASSIGNED_EMPLOYEES: "/company/employees/unassigned",
        ASSIGN_TEAM_TO_EMPLOYEE: (employeeId: string) => `/company/employee/${employeeId}/assign-team`,
        TEAMS: "/company/teams",
        UPDATE_TEAM: (teamId: string) => `/company/team/${teamId}`,
        DELETE_TEAM: (teamId: string) => `/company/team/${teamId}`,
    },
    USER: {
        PROFILE: "/user/profile",
        CHANGE_PASSWORD: "/user/change-password",
    },
    PROJECTS: {
        BASE: "/projects",
        BY_ID: (id: string) => `/projects/${id}`,
    },
    ISSUES: {
        BASE: "/issues",
        BY_PROJECT: (projectId: string) => `/issues/project/${projectId}`,
        BY_SPRINT: (sprintId: string) => `/issues/sprint/${sprintId}`,
        BY_ID: (id: string) => `/issues/${id}`,
        ASSIGN: (id: string) => `/issues/${id}/assign`,
        AUTO_ASSIGN: (id: string) => `/issues/${id}/auto-assign`,
        COMMENT: (id: string) => `/issues/comment/${id}`,
        ATTACHMENT: (id: string) => `/issues/attachment/${id}`,
    },
    TEAMS: {
        BASE: "/teams",
        DIRECTORY: "/teams/directory",
    },
    SPRINTS: {
        BASE: "/sprints",
        BY_ID: (id: string) => `/sprints/${id}`,
    },
    SUBTASKS: {
        BASE: "/subtasks",
        BY_ISSUE: (issueId: string) => `/subtasks/issue/${issueId}`,
        BY_ID: (id: string) => `/subtasks/${id}`,
        ASSIGN: (id: string) => `/subtasks/${id}/assign`,
        AUTO_ASSIGN: (id: string) => `/subtasks/${id}/auto-assign`,
        ASSIGNED: "/subtasks/assigned",
        TEAM: "/subtasks/team",
        ALL: "/subtasks/all",
        START: (id: string) => `/subtasks/start/${id}`,
        SUBMIT: (id: string) => `/subtasks/submit/${id}`,
        REVIEW: (id: string) => `/subtasks/review/${id}`,
        COMMENT: (id: string) => `/subtasks/comment/${id}`,
        ATTACHMENT: (id: string) => `/subtasks/attachment/${id}`,
    },
    UPLOAD: {
        SINGLE: "/upload/single",
        MULTIPLE: "/upload/multiple",
    }
};
