import { Container } from 'inversify';
import { TYPES } from './types';
import { AuthRepository } from '../repositories/auth.repository';
import { AuthController } from '../controller/auth.controller';
import { CompanyRepository } from '../repositories/company.repository';
import { EmployeeRepository } from '../repositories/employee.repository';
import { PermissionRepository } from '../repositories/permission.repository';
import { TeamRepository } from '../repositories/team.repository';
import { IAuthRepository } from '../interfaces/repositories/IAuthRepository';
import { ICompanyRepository } from '../interfaces/repositories/ICompanyRepository';
import { IEmployeeRepository } from '../interfaces/repositories/IEmployeeRepository';
import { IPermissionRepository } from '../interfaces/repositories/IPermissionRepository';
import { ITeamRepository } from '../interfaces/repositories/ITeamRepository';
import { IAddEmployeeService } from '../interfaces/services/employee/IAddEmployeeService';
import { IGetEmployeesService } from '../interfaces/services/employee/IGetEmployeesService';
import { IToggleBlockEmployeeService } from '../interfaces/services/employee/IToggleBlockEmployeeService';
import { IGetEmployeeDetailsService } from '../interfaces/services/employee/IGetEmployeeDetailsService';
import { IUpdateEmployeeDetailsService } from '../interfaces/services/employee/IUpdateEmployeeDetailsService';
import { AddEmployeeService } from '../service/employee/addEmployee.service';
import { GetEmployeesService } from '../service/employee/getEmployees.service';
import { ToggleBlockEmployeeService } from '../service/employee/toggleBlockEmployee.service';
import { GetEmployeeDetailsService } from '../service/employee/getEmployeeDetails.service';
import { UpdateEmployeeDetailsService } from '../service/employee/updateEmployeeDetails.service';
import { ICreateTeamService } from '../interfaces/services/team/ICreateTeamService';
import { IGetTeamsService } from '../interfaces/services/team/IGetTeamsService';
import { IUpdateTeamService } from '../interfaces/services/team/IUpdateTeamService';
import { IDeleteTeamService } from '../interfaces/services/team/IDeleteTeamService';
import { IGetTeamDirectoryService } from '../interfaces/services/team/IGetTeamDirectoryService';
import { CreateTeamService } from '../service/team/createTeam.service';
import { GetTeamsService } from '../service/team/getTeams.service';
import { UpdateTeamService } from '../service/team/updateTeam.service';
import { DeleteTeamService } from '../service/team/deleteTeam.service';
import { GetTeamDirectoryService } from '../service/team/getTeamDirectory.service';
import { IGetProfileService } from '../interfaces/services/user/IGetProfileService';
import { IChangePasswordService } from '../interfaces/services/user/IChangePasswordService';
import { IUpdateUserProfileService } from '../interfaces/services/user/IUpdateUserProfileService';
import { GetProfileService } from '../service/user/getProfile.service';
import { ChangePasswordService } from '../service/user/changePassword.service';
import { UpdateUserProfileService } from '../service/user/updateUserProfile.service';
import { EmployeeController } from '../controller/employee.controller';
import { ProjectRepository } from '../repositories/project.repository';
import { ProjectController } from '../controller/project.controller';
import { IProjectRepository } from '../interfaces/repositories/IProjectRepository';
import { ICreateProjectService } from '../interfaces/services/project/ICreateProjectService';
import { IGetProjectsService } from '../interfaces/services/project/IGetProjectsService';
import { IGetProjectByIdService } from '../interfaces/services/project/IGetProjectByIdService';
import { IUpdateProjectService } from '../interfaces/services/project/IUpdateProjectService';
import { IDeleteProjectService } from '../interfaces/services/project/IDeleteProjectService';
import { CreateProjectService } from '../service/project/createProject.service';
import { GetProjectsService } from '../service/project/getProjects.service';
import { GetProjectByIdService } from '../service/project/getProjectById.service';
import { UpdateProjectService } from '../service/project/updateProject.service';
import { DeleteProjectService } from '../service/project/deleteProject.service';
import { TeamController } from '../controller/team.controller';
import { UserController } from '../controller/user.controller';
import { UserStoryRepository } from '../repositories/userStory.repository';
import { UserStoryController } from '../controller/userStory.controller';
import { IUserStoryRepository } from '../interfaces/repositories/IUserStoryRepository';
import { ICreateUserStoryService } from '../interfaces/services/userStory/ICreateUserStoryService';
import { IGetUserStoriesByProjectService } from '../interfaces/services/userStory/IGetUserStoriesByProjectService';
import { IGetUserStoryByIdService } from '../interfaces/services/userStory/IGetUserStoryByIdService';
import { IUpdateUserStoryService } from '../interfaces/services/userStory/IUpdateUserStoryService';
import { IDeleteUserStoryService } from '../interfaces/services/userStory/IDeleteUserStoryService';
import { CreateUserStoryService } from '../service/userStory/createUserStory.service';
import { GetUserStoriesByProjectService } from '../service/userStory/getUserStoriesByProject.service';
import { GetUserStoryByIdService } from '../service/userStory/getUserStoryById.service';
import { UpdateUserStoryService } from '../service/userStory/updateUserStory.service';
import { DeleteUserStoryService } from '../service/userStory/deleteUserStory.service';
import { IRegisterService } from '../interfaces/services/auth/IRegisterService';
import { IVerifyOtpService } from '../interfaces/services/auth/IVerifyOtpService';
import { IResendOtpService } from '../interfaces/services/auth/IResendOtpService';
import { ILoginService } from '../interfaces/services/auth/ILoginService';
import { IRefreshService } from '../interfaces/services/auth/IRefreshService';
import { ILogoutService } from '../interfaces/services/auth/ILogoutService';
import { IForgotPasswordService } from '../interfaces/services/auth/IForgotPasswordService';
import { IResetPasswordService } from '../interfaces/services/auth/IResetPasswordService';
import { RegisterService } from '../service/auth/register.service';
import { VerifyOtpService } from '../service/auth/verifyOtp.service';
import { ResendOtpService } from '../service/auth/resendOtp.service';
import { LoginService } from '../service/auth/login.service';
import { RefreshService } from '../service/auth/refresh.service';
import { LogoutService } from '../service/auth/logout.service';
import { ForgotPasswordService } from '../service/auth/forgotPassword.service';
import { ResetPasswordService } from '../service/auth/resetPassword.service';

const container = new Container();

container.bind<IAuthRepository>(TYPES.IAuthRepository).to(AuthRepository);
container.bind<ICompanyRepository>(TYPES.ICompanyRepository).to(CompanyRepository);
container.bind<IEmployeeRepository>(TYPES.IEmployeeRepository).to(EmployeeRepository);
container.bind<IPermissionRepository>(TYPES.IPermissionRepository).to(PermissionRepository);
container.bind<ITeamRepository>(TYPES.ITeamRepository).to(TeamRepository);
container.bind<IProjectRepository>(TYPES.IProjectRepository).to(ProjectRepository);
container.bind<IUserStoryRepository>(TYPES.IUserStoryRepository).to(UserStoryRepository);

container.bind<IAddEmployeeService>(TYPES.IAddEmployeeService).to(AddEmployeeService);
container.bind<IGetEmployeesService>(TYPES.IGetEmployeesService).to(GetEmployeesService);
container.bind<IToggleBlockEmployeeService>(TYPES.IToggleBlockEmployeeService).to(ToggleBlockEmployeeService);
container.bind<IGetEmployeeDetailsService>(TYPES.IGetEmployeeDetailsService).to(GetEmployeeDetailsService);
container.bind<IUpdateEmployeeDetailsService>(TYPES.IUpdateEmployeeDetailsService).to(UpdateEmployeeDetailsService);
container.bind<ICreateTeamService>(TYPES.ICreateTeamService).to(CreateTeamService);
container.bind<IGetTeamsService>(TYPES.IGetTeamsService).to(GetTeamsService);
container.bind<IUpdateTeamService>(TYPES.IUpdateTeamService).to(UpdateTeamService);
container.bind<IDeleteTeamService>(TYPES.IDeleteTeamService).to(DeleteTeamService);
container.bind<IGetTeamDirectoryService>(TYPES.IGetTeamDirectoryService).to(GetTeamDirectoryService);
container.bind<IGetProfileService>(TYPES.IGetProfileService).to(GetProfileService);
container.bind<IChangePasswordService>(TYPES.IChangePasswordService).to(ChangePasswordService);
container.bind<IUpdateUserProfileService>(TYPES.IUpdateUserProfileService).to(UpdateUserProfileService);
container.bind<ICreateProjectService>(TYPES.ICreateProjectService).to(CreateProjectService);
container.bind<IGetProjectsService>(TYPES.IGetProjectsService).to(GetProjectsService);
container.bind<IGetProjectByIdService>(TYPES.IGetProjectByIdService).to(GetProjectByIdService);
container.bind<IUpdateProjectService>(TYPES.IUpdateProjectService).to(UpdateProjectService);
container.bind<IDeleteProjectService>(TYPES.IDeleteProjectService).to(DeleteProjectService);
container.bind<ICreateUserStoryService>(TYPES.ICreateUserStoryService).to(CreateUserStoryService);
container.bind<IGetUserStoriesByProjectService>(TYPES.IGetUserStoriesByProjectService).to(GetUserStoriesByProjectService);
container.bind<IGetUserStoryByIdService>(TYPES.IGetUserStoryByIdService).to(GetUserStoryByIdService);
container.bind<IUpdateUserStoryService>(TYPES.IUpdateUserStoryService).to(UpdateUserStoryService);
container.bind<IDeleteUserStoryService>(TYPES.IDeleteUserStoryService).to(DeleteUserStoryService);

container.bind<AuthController>(TYPES.AuthController).to(AuthController);
container.bind<EmployeeController>(TYPES.EmployeeController).to(EmployeeController);
container.bind<TeamController>(TYPES.TeamController).to(TeamController);
container.bind<UserController>(TYPES.UserController).to(UserController);
container.bind<ProjectController>(TYPES.ProjectController).to(ProjectController);
container.bind<UserStoryController>(TYPES.UserStoryController).to(UserStoryController);

container.bind<IRegisterService>(TYPES.IRegisterService).to(RegisterService);
container.bind<IVerifyOtpService>(TYPES.IVerifyOtpService).to(VerifyOtpService);
container.bind<IResendOtpService>(TYPES.IResendOtpService).to(ResendOtpService);
container.bind<ILoginService>(TYPES.ILoginService).to(LoginService);
container.bind<IRefreshService>(TYPES.IRefreshService).to(RefreshService);
container.bind<ILogoutService>(TYPES.ILogoutService).to(LogoutService);
container.bind<IForgotPasswordService>(TYPES.IForgotPasswordService).to(ForgotPasswordService);
container.bind<IResetPasswordService>(TYPES.IResetPasswordService).to(ResetPasswordService);

export { container };
