import { Container } from 'inversify';
import { TYPES } from './types';
import { AuthRepository } from '../repositories/auth.repository';
import { AuthController } from '../controller/auth.controller';
import { CompanyRepository } from '../repositories/company.repository';
import { EmployeeRepository } from '../repositories/employee.repository';
import { PermissionRepository } from '../repositories/permission.repository';
import { TeamRepository } from '../repositories/team.repository';
import { IAuthRepository } from '../interfaces/repositories/IAuthRepository';
import { ICompanyRepository } from '../interfaces/repositories/ICompanyRepository';
import { IEmployeeRepository } from '../interfaces/repositories/IEmployeeRepository';
import { IPermissionRepository } from '../interfaces/repositories/IPermissionRepository';
import { ITeamRepository } from '../interfaces/repositories/ITeamRepository';
import { IAddEmployeeService } from '../interfaces/services/employee/IAddEmployeeService';
import { IGetEmployeesService } from '../interfaces/services/employee/IGetEmployeesService';
import { IToggleBlockEmployeeService } from '../interfaces/services/employee/IToggleBlockEmployeeService';
import { IGetEmployeeDetailsService } from '../interfaces/services/employee/IGetEmployeeDetailsService';
import { IUpdateEmployeeDetailsService } from '../interfaces/services/employee/IUpdateEmployeeDetailsService';
import { IUserService } from '../interfaces/services/IUserService';
import { AddEmployeeService } from '../service/employee/addEmployee.service';
import { GetEmployeesService } from '../service/employee/getEmployees.service';
import { ToggleBlockEmployeeService } from '../service/employee/toggleBlockEmployee.service';
import { GetEmployeeDetailsService } from '../service/employee/getEmployeeDetails.service';
import { UpdateEmployeeDetailsService } from '../service/employee/updateEmployeeDetails.service';
import { ICreateTeamService } from '../interfaces/services/team/ICreateTeamService';
import { IGetTeamsService } from '../interfaces/services/team/IGetTeamsService';
import { IUpdateTeamService } from '../interfaces/services/team/IUpdateTeamService';
import { IDeleteTeamService } from '../interfaces/services/team/IDeleteTeamService';
import { CreateTeamService } from '../service/team/createTeam.service';
import { GetTeamsService } from '../service/team/getTeams.service';
import { UpdateTeamService } from '../service/team/updateTeam.service';
import { DeleteTeamService } from '../service/team/deleteTeam.service';
import { UserService } from '../service/user.service';
import { EmployeeController } from '../controller/employee.controller';
import { ProjectRepository } from '../repositories/project.repository';
import { ProjectController } from '../controller/project.controller';
import { IProjectRepository } from '../interfaces/repositories/IProjectRepository';
import { ICreateProjectService } from '../interfaces/services/project/ICreateProjectService';
import { IGetProjectsService } from '../interfaces/services/project/IGetProjectsService';
import { IGetProjectByIdService } from '../interfaces/services/project/IGetProjectByIdService';
import { IUpdateProjectService } from '../interfaces/services/project/IUpdateProjectService';
import { IDeleteProjectService } from '../interfaces/services/project/IDeleteProjectService';
import { CreateProjectService } from '../service/project/createProject.service';
import { GetProjectsService } from '../service/project/getProjects.service';
import { GetProjectByIdService } from '../service/project/getProjectById.service';
import { UpdateProjectService } from '../service/project/updateProject.service';
import { DeleteProjectService } from '../service/project/deleteProject.service';
import { TeamController } from '../controller/team.controller';
import { UserController } from '../controller/user.controller';
import { UserStoryRepository } from '../repositories/userStory.repository';
import { UserStoryService } from '../service/userStory.service';
import { UserStoryController } from '../controller/userStory.controller';
import { IUserStoryRepository } from '../interfaces/repositories/IUserStoryRepository';
import { IUserStoryService } from '../interfaces/services/IUserStoryService';
import { IRegisterService } from '../interfaces/services/auth/IRegisterService';
import { IVerifyOtpService } from '../interfaces/services/auth/IVerifyOtpService';
import { IResendOtpService } from '../interfaces/services/auth/IResendOtpService';
import { ILoginService } from '../interfaces/services/auth/ILoginService';
import { IRefreshService } from '../interfaces/services/auth/IRefreshService';
import { ILogoutService } from '../interfaces/services/auth/ILogoutService';
import { IForgotPasswordService } from '../interfaces/services/auth/IForgotPasswordService';
import { IResetPasswordService } from '../interfaces/services/auth/IResetPasswordService';
import { RegisterService } from '../service/auth/register.service';
import { VerifyOtpService } from '../service/auth/verifyOtp.service';
import { ResendOtpService } from '../service/auth/resendOtp.service';
import { LoginService } from '../service/auth/login.service';
import { RefreshService } from '../service/auth/refresh.service';
import { LogoutService } from '../service/auth/logout.service';
import { ForgotPasswordService } from '../service/auth/forgotPassword.service';
import { ResetPasswordService } from '../service/auth/resetPassword.service';

const container = new Container();

container.bind<IAuthRepository>(TYPES.AuthRepository).to(AuthRepository);
container.bind<ICompanyRepository>(TYPES.CompanyRepository).to(CompanyRepository);
container.bind<IEmployeeRepository>(TYPES.EmployeeRepository).to(EmployeeRepository);
container.bind<IPermissionRepository>(TYPES.PermissionRepository).to(PermissionRepository);
container.bind<ITeamRepository>(TYPES.TeamRepository).to(TeamRepository);
container.bind<IProjectRepository>(TYPES.ProjectRepository).to(ProjectRepository);
container.bind<IUserStoryRepository>(TYPES.UserStoryRepository).to(UserStoryRepository);

container.bind<IAddEmployeeService>(TYPES.AddEmployeeService).to(AddEmployeeService);
container.bind<IGetEmployeesService>(TYPES.GetEmployeesService).to(GetEmployeesService);
container.bind<IToggleBlockEmployeeService>(TYPES.ToggleBlockEmployeeService).to(ToggleBlockEmployeeService);
container.bind<IGetEmployeeDetailsService>(TYPES.GetEmployeeDetailsService).to(GetEmployeeDetailsService);
container.bind<IUpdateEmployeeDetailsService>(TYPES.UpdateEmployeeDetailsService).to(UpdateEmployeeDetailsService);
container.bind<ICreateTeamService>(TYPES.CreateTeamService).to(CreateTeamService);
container.bind<IGetTeamsService>(TYPES.GetTeamsService).to(GetTeamsService);
container.bind<IUpdateTeamService>(TYPES.UpdateTeamService).to(UpdateTeamService);
container.bind<IDeleteTeamService>(TYPES.DeleteTeamService).to(DeleteTeamService);
container.bind<IUserService>(TYPES.UserService).to(UserService);
container.bind<ICreateProjectService>(TYPES.CreateProjectService).to(CreateProjectService);
container.bind<IGetProjectsService>(TYPES.GetProjectsService).to(GetProjectsService);
container.bind<IGetProjectByIdService>(TYPES.GetProjectByIdService).to(GetProjectByIdService);
container.bind<IUpdateProjectService>(TYPES.UpdateProjectService).to(UpdateProjectService);
container.bind<IDeleteProjectService>(TYPES.DeleteProjectService).to(DeleteProjectService);
container.bind<IUserStoryService>(TYPES.UserStoryService).to(UserStoryService);

container.bind<AuthController>(TYPES.AuthController).to(AuthController);
container.bind<EmployeeController>(TYPES.EmployeeController).to(EmployeeController);
container.bind<TeamController>(TYPES.TeamController).to(TeamController);
container.bind<UserController>(TYPES.UserController).to(UserController);
container.bind<ProjectController>(TYPES.ProjectController).to(ProjectController);
container.bind<UserStoryController>(TYPES.UserStoryController).to(UserStoryController);

container.bind<IRegisterService>(TYPES.RegisterService).to(RegisterService);
container.bind<IVerifyOtpService>(TYPES.VerifyOtpService).to(VerifyOtpService);
container.bind<IResendOtpService>(TYPES.ResendOtpService).to(ResendOtpService);
container.bind<ILoginService>(TYPES.LoginService).to(LoginService);
container.bind<IRefreshService>(TYPES.RefreshService).to(RefreshService);
container.bind<ILogoutService>(TYPES.LogoutService).to(LogoutService);
container.bind<IForgotPasswordService>(TYPES.ForgotPasswordService).to(ForgotPasswordService);
container.bind<IResetPasswordService>(TYPES.ResetPasswordService).to(ResetPasswordService);

export { container };
