import { Container } from 'inversify';
import { TYPES } from './types';
import { AuthRepository } from '../repositories/auth.repository';
import { AuthController } from '../controller/auth.controller';
import { CompanyRepository } from '../repositories/company.repository';
import { EmployeeRepository } from '../repositories/employee.repository';
import { PermissionRepository } from '../repositories/permission.repository';
import { TeamRepository } from '../repositories/team.repository';
import { IAuthRepository } from '../interfaces/repositories/IAuthRepository';
import { ICompanyRepository } from '../interfaces/repositories/ICompanyRepository';
import { IEmployeeRepository } from '../interfaces/repositories/IEmployeeRepository';
import { IPermissionRepository } from '../interfaces/repositories/IPermissionRepository';
import { ITeamRepository } from '../interfaces/repositories/ITeamRepository';
import { IAddEmployeeService } from '../interfaces/services/employee/IAddEmployeeService';
import { IGetEmployeesService } from '../interfaces/services/employee/IGetEmployeesService';
import { IToggleBlockEmployeeService } from '../interfaces/services/employee/IToggleBlockEmployeeService';
import { IGetEmployeeDetailsService } from '../interfaces/services/employee/IGetEmployeeDetailsService';
import { IUpdateEmployeeDetailsService } from '../interfaces/services/employee/IUpdateEmployeeDetailsService';
import { AddEmployeeService } from '../service/employee/addEmployee.service';
import { GetEmployeesService } from '../service/employee/getEmployees.service';
import { ToggleBlockEmployeeService } from '../service/employee/toggleBlockEmployee.service';
import { GetEmployeeDetailsService } from '../service/employee/getEmployeeDetails.service';
import { UpdateEmployeeDetailsService } from '../service/employee/updateEmployeeDetails.service';
import { IGetUnassignedEmployeesService } from '../interfaces/services/employee/IGetUnassignedEmployeesService';
import { IAssignTeamToEmployeeService } from '../interfaces/services/employee/IAssignTeamToEmployeeService';
import { GetUnassignedEmployeesService } from '../service/employee/getUnassignedEmployees.service';
import { AssignTeamToEmployeeService } from '../service/employee/assignTeamToEmployee.service';
import { ICreateTeamService } from '../interfaces/services/team/ICreateTeamService';
import { IGetTeamsService } from '../interfaces/services/team/IGetTeamsService';
import { IUpdateTeamService } from '../interfaces/services/team/IUpdateTeamService';
import { IDeleteTeamService } from '../interfaces/services/team/IDeleteTeamService';
import { IGetTeamDirectoryService } from '../interfaces/services/team/IGetTeamDirectoryService';
import { CreateTeamService } from '../service/team/createTeam.service';
import { GetTeamsService } from '../service/team/getTeams.service';
import { UpdateTeamService } from '../service/team/updateTeam.service';
import { DeleteTeamService } from '../service/team/deleteTeam.service';
import { GetTeamDirectoryService } from '../service/team/getTeamDirectory.service';
import { IGetProfileService } from '../interfaces/services/user/IGetProfileService';
import { IChangePasswordService } from '../interfaces/services/user/IChangePasswordService';
import { IUpdateUserProfileService } from '../interfaces/services/user/IUpdateUserProfileService';
import { GetProfileService } from '../service/user/getProfile.service';
import { ChangePasswordService } from '../service/user/changePassword.service';
import { UpdateUserProfileService } from '../service/user/updateUserProfile.service';
import { EmployeeController } from '../controller/employee.controller';
import { ProjectRepository } from '../repositories/project.repository';
import { ProjectController } from '../controller/project.controller';
import { IProjectRepository } from '../interfaces/repositories/IProjectRepository';
import { ICreateProjectService } from '../interfaces/services/project/ICreateProjectService';
import { IGetProjectsService } from '../interfaces/services/project/IGetProjectsService';
import { IGetProjectByIdService } from '../interfaces/services/project/IGetProjectByIdService';
import { IUpdateProjectService } from '../interfaces/services/project/IUpdateProjectService';
import { IDeleteProjectService } from '../interfaces/services/project/IDeleteProjectService';
import { IGetProjectInsightsService } from '../interfaces/services/project/IGetProjectInsightsService';
import { CreateProjectService } from '../service/project/createProject.service';
import { GetProjectsService } from '../service/project/getProjects.service';
import { GetProjectByIdService } from '../service/project/getProjectById.service';
import { UpdateProjectService } from '../service/project/updateProject.service';
import { DeleteProjectService } from '../service/project/deleteProject.service';
import { GetProjectInsightsService } from '../service/project/getProjectInsights.service';
import { TeamController } from '../controller/team.controller';
import { UserController } from '../controller/user.controller';
import { IssueRepository } from '../repositories/issue.repository';
import { IssueController } from '../controller/issue.controller';
import { IIssueRepository } from '../interfaces/repositories/IIssueRepository';
import { UploadController } from '../controller/upload.controller';
import { IGetCompanyDashboardService } from '../interfaces/services/dashboard/IGetCompanyDashboardService';
import { GetCompanyDashboardService } from '../service/dashboard/GetCompanyDashboardService';
import { IGetEmployeeDashboardService } from '../interfaces/services/dashboard/IGetEmployeeDashboardService';
import { GetEmployeeDashboardService } from '../service/dashboard/GetEmployeeDashboardService';
import { DashboardController } from '../controller/dashboard.controller';

// Issue Services
import { ICreateIssueService } from '../interfaces/services/issue/ICreateIssueService';
import { IGetIssuesByProjectService } from '../interfaces/services/issue/IGetIssuesByProjectService';
import { IGetIssuesBySprintService } from '../interfaces/services/issue/IGetIssuesBySprintService';
import { IGetIssueByIdService } from '../interfaces/services/issue/IGetIssueByIdService';
import { IUpdateIssueService } from '../interfaces/services/issue/IUpdateIssueService';
import { IDeleteIssueService } from '../interfaces/services/issue/IDeleteIssueService';
import { IAssignIssueService } from '../interfaces/services/issue/IAssignIssueService';
import { CreateIssueService } from '../service/issue/CreateIssueService';
import { GetIssuesByProjectService } from '../service/issue/GetIssuesByProjectService';
import { GetIssuesBySprintService } from '../service/issue/GetIssuesBySprintService';
import { GetIssueByIdService } from '../service/issue/GetIssueByIdService';
import { UpdateIssueService } from '../service/issue/UpdateIssueService';
import { DeleteIssueService } from '../service/issue/DeleteIssueService';
import { AssignIssueService } from '../service/issue/AssignIssueService';
import { IAddCommentToIssueService } from '../interfaces/services/issue/IAddCommentToIssueService';
import { AddCommentToIssueService } from '../service/issue/AddCommentToIssueService';

import { IAddAttachmentToIssueService } from '../interfaces/services/issue/IAddAttachmentToIssueService';
import { AddAttachmentToIssueService } from '../service/issue/AddAttachmentToIssueService';

// Auth Services
import { IRegisterService } from '../interfaces/services/auth/IRegisterService';
import { IVerifyOtpService } from '../interfaces/services/auth/IVerifyOtpService';
import { IResendOtpService } from '../interfaces/services/auth/IResendOtpService';
import { ILoginService } from '../interfaces/services/auth/ILoginService';
import { IRefreshService } from '../interfaces/services/auth/IRefreshService';
import { ILogoutService } from '../interfaces/services/auth/ILogoutService';
import { IForgotPasswordService } from '../interfaces/services/auth/IForgotPasswordService';
import { IResetPasswordService } from '../interfaces/services/auth/IResetPasswordService';
import { RegisterService } from '../service/auth/register.service';
import { VerifyOtpService } from '../service/auth/verifyOtp.service';
import { ResendOtpService } from '../service/auth/resendOtp.service';
import { LoginService } from '../service/auth/login.service';
import { RefreshService } from '../service/auth/refresh.service';
import { LogoutService } from '../service/auth/logout.service';
import { ForgotPasswordService } from '../service/auth/forgotPassword.service';
import { ResetPasswordService } from '../service/auth/resetPassword.service';

// Sprint Services
import { ISprintRepository } from '../interfaces/repositories/ISprintRepository';
import { SprintRepository } from '../repositories/sprint.repository';
import { ICreateSprintService } from '../interfaces/services/sprint/ICreateSprintService';
import { IGetSprintsService } from '../interfaces/services/sprint/IGetSprintsService';
import { IUpdateSprintService } from '../interfaces/services/sprint/IUpdateSprintService';
import { IDeleteSprintService } from '../interfaces/services/sprint/IDeleteSprintService';
import { IGetSprintByIdService } from '../interfaces/services/sprint/IGetSprintByIdService';
import { CreateSprintService } from '../service/sprint/createSprint.Service';
import { GetSprintsService } from '../service/sprint/getSprints.service';
import { UpdateSprintService } from '../service/sprint/updateSprint.service';
import { DeleteSprintService } from '../service/sprint/deleteSprint.service';
import { GetSprintByIdService } from '../service/sprint/getSprintById.service';
import { IVelocityService } from '../interfaces/services/sprint/IVelocityService';
import { VelocityService } from '../service/sprint/VelocityService';
import { SprintController } from '../controller/sprint.controller';

// SubTask Services
import { ISubTaskRepository } from '../interfaces/repositories/ISubTaskRepository';
import { SubTaskRepository } from '../repositories/subTask.repository';
import { ICreateSubTaskService } from '../interfaces/services/subTask/ICreateSubTaskService';
import { IUpdateSubTaskService } from '../interfaces/services/subTask/IUpdateSubTaskService';
import { IDeleteSubTaskService } from '../interfaces/services/subTask/IDeleteSubTaskService';
import { IGetSubTaskByIdService } from '../interfaces/services/subTask/IGetSubTaskByIdService';
import { IGetSubTasksByIssueService } from '../interfaces/services/subTask/IGetSubTasksByIssueService';
import { IAssignSubTaskService } from '../interfaces/services/subTask/IAssignSubTaskService';
import { IGetAssignedSubTasksService } from '../interfaces/services/subTask/IGetAssignedSubTasksService';
import { IGetTeamSubTasksService } from '../interfaces/services/subTask/IGetTeamSubTasksService';
import { IGetAllSubTasksService } from '../interfaces/services/subTask/IGetAllSubTasksService';
import { IStartSubTaskService } from '../interfaces/services/subTask/IStartSubTaskService';
import { ISubmitSubTaskService } from '../interfaces/services/subTask/ISubmitSubTaskService';
import { IReviewSubTaskService } from '../interfaces/services/subTask/IReviewSubTaskService';
import { CreateSubTaskService } from '../service/subTask/CreateSubTaskService';
import { UpdateSubTaskService } from '../service/subTask/UpdateSubTaskService';
import { DeleteSubTaskService } from '../service/subTask/DeleteSubTaskService';
import { GetSubTaskByIdService } from '../service/subTask/GetSubTaskByIdService';
import { GetSubTasksByIssueService } from '../service/subTask/GetSubTasksByIssueService';
import { AssignSubTaskService } from '../service/subTask/AssignSubTaskService';
import { GetAssignedSubTasksService } from '../service/subTask/GetAssignedSubTasksService';
import { GetTeamSubTasksService } from '../service/subTask/GetTeamSubTasksService';
import { GetAllSubTasksService } from '../service/subTask/GetAllSubTasksService';
import { StartSubTaskService } from '../service/subTask/StartSubTaskService';
import { SubmitSubTaskService } from '../service/subTask/SubmitSubTaskService';
import { ReviewSubTaskService } from '../service/subTask/ReviewSubTaskService';
import { IAddCommentToSubTaskService } from '../interfaces/services/subTask/IAddCommentToSubTaskService';
import { AddCommentToSubTaskService } from '../service/subTask/AddCommentToSubTaskService';
import { IAddAttachmentToSubTaskService } from '../interfaces/services/subTask/IAddAttachmentToSubTaskService';
import { AddAttachmentToSubTaskService } from '../service/subTask/AddAttachmentToSubTaskService';
import { SubTaskController } from '../controller/subTask.controller';

// Notification & Socket
import { ISocketService } from '../interfaces/services/ISocketService';
import { SocketService } from '../utils/socket.service';
import { INotificationRepository } from '../interfaces/repositories/INotificationRepository';
import { NotificationRepository } from '../repositories/notification.repository';
import { INotificationService } from '../interfaces/services/INotificationService';
import { NotificationService } from '../service/notification.service';
import { NotificationController } from '../controller/notification.controller';
import { IStorageProvider } from '../interfaces/providers/IStorageProvider';
import { S3StorageProvider } from '../providers/S3StorageProvider';
import { IAIService } from '../interfaces/services/ai/IAIService';
import { AIService } from '../service/ai/ai.service';
import { IAutoAssignSubTaskService } from '../interfaces/services/subTask/IAutoAssignSubTaskService';
import { AutoAssignSubTaskService } from '../service/subTask/AutoAssignSubTaskService';
import { IAutoAssignIssueService } from '../interfaces/services/issue/IAutoAssignIssueService';
import { AutoAssignIssueService } from '../service/issue/AutoAssignIssueService';
const container = new Container();

container.bind<IAuthRepository>(TYPES.IAuthRepository).to(AuthRepository);
container.bind<ICompanyRepository>(TYPES.ICompanyRepository).to(CompanyRepository);
container.bind<IEmployeeRepository>(TYPES.IEmployeeRepository).to(EmployeeRepository);
container.bind<IPermissionRepository>(TYPES.IPermissionRepository).to(PermissionRepository);
container.bind<ITeamRepository>(TYPES.ITeamRepository).to(TeamRepository);
container.bind<IProjectRepository>(TYPES.IProjectRepository).to(ProjectRepository);
container.bind<IIssueRepository>(TYPES.IIssueRepository).to(IssueRepository);
container.bind<ISprintRepository>(TYPES.ISprintRepository).to(SprintRepository);
container.bind<ISubTaskRepository>(TYPES.ISubTaskRepository).to(SubTaskRepository);
container.bind<INotificationRepository>(TYPES.INotificationRepository).to(NotificationRepository);

container.bind<ISocketService>(TYPES.ISocketService).to(SocketService).inSingletonScope();

container.bind<IAddEmployeeService>(TYPES.IAddEmployeeService).to(AddEmployeeService);
container.bind<IGetEmployeesService>(TYPES.IGetEmployeesService).to(GetEmployeesService);
container.bind<IToggleBlockEmployeeService>(TYPES.IToggleBlockEmployeeService).to(ToggleBlockEmployeeService);
container.bind<IGetEmployeeDetailsService>(TYPES.IGetEmployeeDetailsService).to(GetEmployeeDetailsService);
container.bind<IUpdateEmployeeDetailsService>(TYPES.IUpdateEmployeeDetailsService).to(UpdateEmployeeDetailsService);
container.bind<IGetUnassignedEmployeesService>(TYPES.IGetUnassignedEmployeesService).to(GetUnassignedEmployeesService);
container.bind<IAssignTeamToEmployeeService>(TYPES.IAssignTeamToEmployeeService).to(AssignTeamToEmployeeService);
container.bind<ICreateTeamService>(TYPES.ICreateTeamService).to(CreateTeamService);
container.bind<IGetTeamsService>(TYPES.IGetTeamsService).to(GetTeamsService);
container.bind<IUpdateTeamService>(TYPES.IUpdateTeamService).to(UpdateTeamService);
container.bind<IDeleteTeamService>(TYPES.IDeleteTeamService).to(DeleteTeamService);
container.bind<IGetTeamDirectoryService>(TYPES.IGetTeamDirectoryService).to(GetTeamDirectoryService);
container.bind<IGetProfileService>(TYPES.IGetProfileService).to(GetProfileService);
container.bind<IChangePasswordService>(TYPES.IChangePasswordService).to(ChangePasswordService);
container.bind<IUpdateUserProfileService>(TYPES.IUpdateUserProfileService).to(UpdateUserProfileService);
container.bind<ICreateProjectService>(TYPES.ICreateProjectService).to(CreateProjectService);
container.bind<IGetProjectsService>(TYPES.IGetProjectsService).to(GetProjectsService);
container.bind<IGetProjectByIdService>(TYPES.IGetProjectByIdService).to(GetProjectByIdService);
container.bind<IUpdateProjectService>(TYPES.IUpdateProjectService).to(UpdateProjectService);
container.bind<IDeleteProjectService>(TYPES.IDeleteProjectService).to(DeleteProjectService);
container.bind<IGetProjectInsightsService>(TYPES.IGetProjectInsightsService).to(GetProjectInsightsService);

container.bind<ICreateIssueService>(TYPES.ICreateIssueService).to(CreateIssueService);
container.bind<IGetIssuesByProjectService>(TYPES.IGetIssuesByProjectService).to(GetIssuesByProjectService);
container.bind<IGetIssuesBySprintService>(TYPES.IGetIssuesBySprintService).to(GetIssuesBySprintService);
container.bind<IGetIssueByIdService>(TYPES.IGetIssueByIdService).to(GetIssueByIdService);
container.bind<IUpdateIssueService>(TYPES.IUpdateIssueService).to(UpdateIssueService);
container.bind<IDeleteIssueService>(TYPES.IDeleteIssueService).to(DeleteIssueService);
container.bind<IAssignIssueService>(TYPES.IAssignIssueService).to(AssignIssueService);
container.bind<IAddCommentToIssueService>(TYPES.IAddCommentToIssueService).to(AddCommentToIssueService);
container.bind<IAddAttachmentToIssueService>(TYPES.IAddAttachmentToIssueService).to(AddAttachmentToIssueService);

container.bind<ICreateSprintService>(TYPES.ICreateSprintService).to(CreateSprintService);
container.bind<IGetSprintsService>(TYPES.IGetSprintsService).to(GetSprintsService);
container.bind<IUpdateSprintService>(TYPES.IUpdateSprintService).to(UpdateSprintService);
container.bind<IDeleteSprintService>(TYPES.IDeleteSprintService).to(DeleteSprintService);
container.bind<IGetSprintByIdService>(TYPES.IGetSprintByIdService).to(GetSprintByIdService);
container.bind<IVelocityService>(TYPES.IVelocityService).to(VelocityService);

container.bind<ICreateSubTaskService>(TYPES.ICreateSubTaskService).to(CreateSubTaskService);
container.bind<IUpdateSubTaskService>(TYPES.IUpdateSubTaskService).to(UpdateSubTaskService);
container.bind<IDeleteSubTaskService>(TYPES.IDeleteSubTaskService).to(DeleteSubTaskService);
container.bind<IGetSubTaskByIdService>(TYPES.IGetSubTaskByIdService).to(GetSubTaskByIdService);
container.bind<IGetSubTasksByIssueService>(TYPES.IGetSubTasksByIssueService).to(GetSubTasksByIssueService);
container.bind<IAssignSubTaskService>(TYPES.IAssignSubTaskService).to(AssignSubTaskService);
container.bind<IGetAssignedSubTasksService>(TYPES.IGetAssignedSubTasksService).to(GetAssignedSubTasksService);
container.bind<IGetTeamSubTasksService>(TYPES.IGetTeamSubTasksService).to(GetTeamSubTasksService);
container.bind<IGetAllSubTasksService>(TYPES.IGetAllSubTasksService).to(GetAllSubTasksService);
container.bind<IStartSubTaskService>(TYPES.IStartSubTaskService).to(StartSubTaskService);
container.bind<ISubmitSubTaskService>(TYPES.ISubmitSubTaskService).to(SubmitSubTaskService);
container.bind<IReviewSubTaskService>(TYPES.IReviewSubTaskService).to(ReviewSubTaskService);
container.bind<IAddCommentToSubTaskService>(TYPES.IAddCommentToSubTaskService).to(AddCommentToSubTaskService);
container.bind<IAddAttachmentToSubTaskService>(TYPES.IAddAttachmentToSubTaskService).to(AddAttachmentToSubTaskService);
container.bind<IGetCompanyDashboardService>(TYPES.IGetCompanyDashboardService).to(GetCompanyDashboardService);
container.bind<IGetEmployeeDashboardService>(TYPES.IGetEmployeeDashboardService).to(GetEmployeeDashboardService);
container.bind<INotificationService>(TYPES.INotificationService).to(NotificationService);

container.bind<AuthController>(TYPES.AuthController).to(AuthController);
container.bind<EmployeeController>(TYPES.EmployeeController).to(EmployeeController);
container.bind<TeamController>(TYPES.TeamController).to(TeamController);
container.bind<UserController>(TYPES.UserController).to(UserController);
container.bind<ProjectController>(TYPES.ProjectController).to(ProjectController);
container.bind<IssueController>(TYPES.IssueController).to(IssueController);
container.bind<SprintController>(TYPES.SprintController).to(SprintController);
container.bind<SubTaskController>(TYPES.SubTaskController).to(SubTaskController);
container.bind<UploadController>(TYPES.UploadController).to(UploadController);
container.bind<DashboardController>(TYPES.DashboardController).to(DashboardController);
container.bind<NotificationController>(TYPES.NotificationController).to(NotificationController);

container.bind<IRegisterService>(TYPES.IRegisterService).to(RegisterService);
container.bind<IVerifyOtpService>(TYPES.IVerifyOtpService).to(VerifyOtpService);
container.bind<IResendOtpService>(TYPES.IResendOtpService).to(ResendOtpService);
container.bind<ILoginService>(TYPES.ILoginService).to(LoginService);
container.bind<IRefreshService>(TYPES.IRefreshService).to(RefreshService);
container.bind<ILogoutService>(TYPES.ILogoutService).to(LogoutService);
container.bind<IForgotPasswordService>(TYPES.IForgotPasswordService).to(ForgotPasswordService);
container.bind<IResetPasswordService>(TYPES.IResetPasswordService).to(ResetPasswordService);

container.bind<IStorageProvider>(TYPES.IStorageProvider).to(S3StorageProvider);
container.bind<IAIService>(TYPES.IAIService).to(AIService);
container.bind<IAutoAssignSubTaskService>(TYPES.IAutoAssignSubTaskService).to(AutoAssignSubTaskService);
container.bind<IAutoAssignIssueService>(TYPES.IAutoAssignIssueService).to(AutoAssignIssueService);

export { container };
